"""Добалено тестирование для домашек

Revision ID: 1721e0b8c905
Revises: 544c9c58dcbe
Create Date: 2025-04-21 12:35:56.799873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1721e0b8c905'
down_revision: Union[str, None] = '544c9c58dcbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
