"""тренажер

Revision ID: 1902c59def0c
Revises: ecd6ca75abb8
Create Date: 2025-04-08 13:42:43.242745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1902c59def0c'
down_revision: Union[str, None] = 'ecd6ca75abb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_task_attachments', sa.Column('attachment_type', sa.Enum('task_file', 'task_image', 'solution_file', 'solution_image', name='exam_task_attachment_type'), nullable=False))
    op.drop_column('exam_task_attachments', 'file_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_task_attachments', sa.Column('file_type', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('exam_task_attachments', 'attachment_type')
    # ### end Alembic commands ###
