"""Добавлены даты отклиокв

Revision ID: 4178420d163e
Revises: c284034841e5
Create Date: 2025-02-27 15:14:26.073064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4178420d163e'
down_revision: Union[str, None] = 'c284034841e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework_submissions', sa.Column('client_submission_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework_submissions', 'client_submission_time')
    # ### end Alembic commands ###
