"""тренаже2р

Revision ID: 4dc523178346
Revises: 1902c59def0c
Create Date: 2025-04-08 13:51:55.708414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc523178346'
down_revision: Union[str, None] = '1902c59def0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_tasks', sa.Column('solution_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_tasks', 'solution_text')
    # ### end Alembic commands ###
