"""До

Revision ID: 51a9a0b555c5
Revises: a51b676f6e6c
Create Date: 2025-03-10 14:08:41.625038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51a9a0b555c5'
down_revision: Union[str, None] = 'a51b676f6e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework_submissions', sa.Column('modified_submission_time', sa.DateTime(), nullable=True))
    op.alter_column('homework_submissions', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('submitted', 'graded', 'pending', 'checked', name='submission_status'),
               existing_nullable=True)
    op.drop_column('homework_submissions', 'submission_date')
    op.add_column('homeworks', sa.Column('status', sa.Enum('dosed', 'current', name='homework_status'), nullable=True))
    op.drop_column('teacher_responses', 'teacher_grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_responses', sa.Column('teacher_grade', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('homeworks', 'status')
    op.add_column('homework_submissions', sa.Column('submission_date', mysql.DATETIME(), nullable=True))
    op.alter_column('homework_submissions', 'status',
               existing_type=sa.Enum('submitted', 'graded', 'pending', 'checked', name='submission_status'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('homework_submissions', 'modified_submission_time')
    # ### end Alembic commands ###
