"""Добавил каскадное удаление для уроков, домашних и сабмишенов

Revision ID: 544c9c58dcbe
Revises: 2b6d1204d465
Create Date: 2025-04-18 11:54:35.082900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '544c9c58dcbe'
down_revision: Union[str, None] = '2b6d1204d465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exam_task_attachments_ibfk_1', 'exam_task_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'exam_task_attachments', 'exam_tasks', ['exam_task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('grades', 'submission_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('grades_ibfk_1', 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'homework_submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.alter_column('homework_files', 'submission_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('homework_files_ibfk_1', 'homework_files', type_='foreignkey')
    op.create_foreign_key(None, 'homework_files', 'homework_submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('homework_groups_ibfk_2', 'homework_groups', type_='foreignkey')
    op.drop_constraint('homework_groups_ibfk_1', 'homework_groups', type_='foreignkey')
    op.create_foreign_key(None, 'homework_groups', 'homeworks', ['homework_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'homework_groups', 'study_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('homework_submissions', 'homework_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('homework_submissions_ibfk_1', 'homework_submissions', type_='foreignkey')
    op.drop_constraint('homework_submissions_ibfk_2', 'homework_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'homework_submissions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'homework_submissions', 'homeworks', ['homework_id'], ['id'], ondelete='CASCADE')
    op.alter_column('homeworks', 'lesson_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('homeworks_ibfk_1', 'homeworks', type_='foreignkey')
    op.create_foreign_key(None, 'homeworks', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lesson_groups_ibfk_2', 'lesson_groups', type_='foreignkey')
    op.drop_constraint('lesson_groups_ibfk_1', 'lesson_groups', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_groups', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lesson_groups', 'study_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('refresh_tokens_ibfk_1', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('teacher_response_files', 'teacher_response_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('teacher_response_files_ibfk_1', 'teacher_response_files', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_response_files', 'teacher_responses', ['teacher_response_id'], ['id'], ondelete='CASCADE')
    op.alter_column('teacher_responses', 'submission_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('teacher_responses_ibfk_1', 'teacher_responses', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_responses', 'homework_submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('test_sessions_ibfk_1', 'test_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'test_sessions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'study_groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'study_groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'test_sessions', type_='foreignkey')
    op.create_foreign_key('test_sessions_ibfk_1', 'test_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'teacher_responses', type_='foreignkey')
    op.create_foreign_key('teacher_responses_ibfk_1', 'teacher_responses', 'homework_submissions', ['submission_id'], ['id'])
    op.alter_column('teacher_responses', 'submission_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'teacher_response_files', type_='foreignkey')
    op.create_foreign_key('teacher_response_files_ibfk_1', 'teacher_response_files', 'teacher_responses', ['teacher_response_id'], ['id'])
    op.alter_column('teacher_response_files', 'teacher_response_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_ibfk_1', 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'lesson_groups', type_='foreignkey')
    op.drop_constraint(None, 'lesson_groups', type_='foreignkey')
    op.create_foreign_key('lesson_groups_ibfk_1', 'lesson_groups', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key('lesson_groups_ibfk_2', 'lesson_groups', 'study_groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'homeworks', type_='foreignkey')
    op.create_foreign_key('homeworks_ibfk_1', 'homeworks', 'lessons', ['lesson_id'], ['id'])
    op.alter_column('homeworks', 'lesson_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'homework_submissions', type_='foreignkey')
    op.drop_constraint(None, 'homework_submissions', type_='foreignkey')
    op.create_foreign_key('homework_submissions_ibfk_2', 'homework_submissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('homework_submissions_ibfk_1', 'homework_submissions', 'homeworks', ['homework_id'], ['id'])
    op.alter_column('homework_submissions', 'homework_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'homework_groups', type_='foreignkey')
    op.drop_constraint(None, 'homework_groups', type_='foreignkey')
    op.create_foreign_key('homework_groups_ibfk_1', 'homework_groups', 'homeworks', ['homework_id'], ['id'])
    op.create_foreign_key('homework_groups_ibfk_2', 'homework_groups', 'study_groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'homework_files', type_='foreignkey')
    op.create_foreign_key('homework_files_ibfk_1', 'homework_files', 'homework_submissions', ['submission_id'], ['id'])
    op.alter_column('homework_files', 'submission_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key('grades_ibfk_1', 'grades', 'homework_submissions', ['submission_id'], ['id'])
    op.alter_column('grades', 'submission_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'exam_task_attachments', type_='foreignkey')
    op.create_foreign_key('exam_task_attachments_ibfk_1', 'exam_task_attachments', 'exam_tasks', ['exam_task_id'], ['id'])
    # ### end Alembic commands ###
