"""ctccb

Revision ID: 5a43e418dbed
Revises: 3505104846d1
Create Date: 2025-04-22 13:17:59.559939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a43e418dbed'
down_revision: Union[str, None] = '3505104846d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sessions', sa.Column('homework_test_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_sessions', 'homework_tests', ['homework_test_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_sessions', type_='foreignkey')
    op.drop_column('test_sessions', 'homework_test_id')
    # ### end Alembic commands ###
