"""убран фингер

Revision ID: 6e4fd408d7b0
Revises: bf01f4dbb23e
Create Date: 2025-03-12 13:31:55.138912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4fd408d7b0'
down_revision: Union[str, None] = 'bf01f4dbb23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
