"""Add response_received status to homework_submissiыons

Revision ID: 8f80aa11f684
Revises: d432a1561e12
Create Date: 2025-03-10 15:45:13.930808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f80aa11f684'
down_revision: Union[str, None] = 'd432a1561e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
