"""Добавлены таблицы отклика препода

Revision ID: a51b676f6e6c
Revises: e2bf18d5668f
Create Date: 2025-03-06 13:21:05.470625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51b676f6e6c'
down_revision: Union[str, None] = 'e2bf18d5668f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('teacher_grade', sa.Integer(), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['homework_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_teacher_responses_id'), 'teacher_responses', ['id'], unique=False)
    op.create_table('teacher_response_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_response_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_response_id'], ['teacher_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_response_files_id'), 'teacher_response_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_response_files_id'), table_name='teacher_response_files')
    op.drop_table('teacher_response_files')
    op.drop_index(op.f('ix_teacher_responses_id'), table_name='teacher_responses')
    op.drop_table('teacher_responses')
    # ### end Alembic commands ###
