"""Добалено тестирование для домашек

Revision ID: abd90041dfe3
Revises: 1721e0b8c905
Create Date: 2025-04-21 13:28:01.021417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd90041dfe3'
down_revision: Union[str, None] = '1721e0b8c905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework_tests', sa.Column('tasks_meta', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework_tests', 'tasks_meta')
    # ### end Alembic commands ###
