"""Добавлен group_id в lessons и homeworks

Revision ID: c284034841e5
Revises: d8f2cecfcd63
Create Date: 2025-02-27 10:10:05.063519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c284034841e5'
down_revision: Union[str, None] = 'd8f2cecfcd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_homeworks_group_id'), 'homeworks', ['group_id'], unique=False)
    op.create_foreign_key(None, 'homeworks', 'groups', ['group_id'], ['id'])
    op.add_column('lessons', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lessons_group_id'), 'lessons', ['group_id'], unique=False)
    op.create_foreign_key(None, 'lessons', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_group_id'), table_name='lessons')
    op.drop_column('lessons', 'group_id')
    op.drop_constraint(None, 'homeworks', type_='foreignkey')
    op.drop_index(op.f('ix_homeworks_group_id'), table_name='homeworks')
    op.drop_column('homeworks', 'group_id')
    # ### end Alembic commands ###
