"""Добавлен колонка для линковки изображений в домашке

Revision ID: e2bf18d5668f
Revises: 4178420d163e
Create Date: 2025-02-27 16:23:46.851884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bf18d5668f'
down_revision: Union[str, None] = '4178420d163e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('images', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homeworks', 'images')
    # ### end Alembic commands ###
