"""Fix study_groups migration

Revision ID: eeadddfb2b9a
Revises: 91de6148b405
Create Date: 2025-03-13 10:45:48.407341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeadddfb2b9a'
down_revision: Union[str, None] = '91de6148b405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_homeworks_id'), 'homeworks', ['id'], unique=False)
    op.create_foreign_key(None, 'users', 'study_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_homeworks_id'), table_name='homeworks')
    # ### end Alembic commands ###
